server:
  port: 8082

#spring:
#  cloud:
#    gateway:
#      routes:
#        #http://localhost:8082/provider/name/?name=zhangsan
#        - id: api_route
#          uri: http://localhost:8083
#          predicates:
#            - Path=/provider/**

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace