server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: api-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/api_backend?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
#    url: jdbc:mysql://192.168.239.128:3306/api_backend
    username: root
    password: 11111111
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
#    host: 192.168.239.128
    database: 0
  #springCache配置
  cache:
    redis:
      time-to-live: 180000 #缓存时间30分钟
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

upload:
  filePath: F:\

dubbo:
  application:
    name: api-backend
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848